### ISSUE TITLE
Javascript errors under jupyter

### ISSUE THREAD

**Issue by damienpolizzi** [lgpage/nbtutor#35] opened 2018-10-09 10:56 UTC
I've install in my python repository

./pip --proxy=proxy.utbm.fr:3128 install nbtutor
./jupyter nbextension install --overwrite --py nbtutor --sys-prefix
./jupyter nbextension enable nbtutor --py --sys-prefix

now in a notebook I have in a first cell :
`%load_ext nbtutor`

and in a second cell :
`%%nbtutor
blutch = 7
print (blutch)
`

then I execute the code in the first cell, nothing appends

And now in a second cell, nothing happends but I have this exception (just replacing my login by ...) in my javascript console (firefox):
`Exception in event handler for toolbar_rebuild.CellToolbar
InternalError
​
columnNumber: 13
​
fileName: "http://localhost:8080/user/.../static/notebook/js/main.min.js?v=fc2a61bcf6f091823db7fb553a838e7f"
​
lineNumber: 28677
​
message: "too much recursion"
​
stack: "events.trigger@http://localhost:8080/user/.../static/notebook/js/main.min.js?v=fc2a61bcf6f091823db7fb553a838e7f:28677:13\nCellToolbar.prototype.rebuild@http://localhost:8080/user/.../nbextensions/create_assignment/main.js?v=20181009123455:22:9\nCellToolbar.prototype.rebuild@http://localhost:8080/user/.../nbextensions/create_assignment/main.js?v=20181009123455:23:9\nCellToolbar.prototype.rebuild@http://localhost:8080/user/.../nbextensions/create_assignment/main.js?v=20181009123455:23:9\nCellToolbar.prototype.rebuild@http://localhost:8080/user/.../nbextensions/create_assignment/main.js?v=20181009123455:23:9\nCellToolbar.prototype.rebuild@http://localhost:8080/user/.../nbextensions/create_assignment/main.js?v=20181009123455:23:9\nCellToolbar.prototype.rebuild@http://localhost:8080/user/.../nbextensions/create_assignment/main.js?v=20181009123455:23:9\nCellToolbar.prototype.rebuild@http://localhost:8080/user/..../nbextensions/create_assignment/main.js?v=20181…"
​
__proto__: Object { stack: "", … }
 Arguments
​0: "toolbar_rebuild.CellToolbar"
​1: Object { selected: false, anchor: false, rendered: true, … }
​callee: Getter & Setter
​length: 2
​Symbol(Symbol.iterator): function values()
​__proto__: {…}
​​__defineGetter__: function __defineGetter__()
​​__defineSetter__: function __defineSetter__()
​​__lookupGetter__: function __lookupGetter__()
​​__lookupSetter__: function __lookupSetter__()
​​constructor: function Object()
​​hasOwnProperty: function hasOwnProperty()
​​isPrototypeOf: function isPrototypeOf()
​​propertyIsEnumerable: function propertyIsEnumerable()
​​toLocaleString: function toLocaleString()
​​toSource: function toSource()
​​toString: function toString()
​​valueOf: function valueOf()
`

**Comment by damienpolizzi** [comment] 2018-10-09 11:01
Just ading the fact I'm using python 3.7 and this packages

./pip list
alembic                           1.0.0    
async-generator                   1.10     
backcall                          0.1.0    
bleach                            2.1.4    
certifi                           2018.8.24
chardet                           3.0.4    
decorator                         4.3.0    
defusedxml                        0.5.0    
entrypoints                       0.2.3    
html5lib                          1.0.1    
idna                              2.7      
ipykernel                         4.9.0    
ipython                           6.5.0    
ipython-genutils                  0.2.0    
ipywidgets                        7.4.2    
jedi                              0.12.1   
jhub-cas-authenticator            0.3.0    
Jinja2                            2.10     
jsonschema                        2.6.0    
jupyter                           1.0.0    
jupyter-c-kernel                  1.2.2    
jupyter-client                    5.2.3    
jupyter-console                   5.2.0    
jupyter-contrib-core              0.3.3    
jupyter-contrib-nbextensions      0.5.0    
jupyter-core                      4.4.0    
jupyter-highlight-selected-word   0.2.0    
jupyter-latex-envs                1.4.4    
jupyter-nbextensions-configurator 0.4.0    
jupyterhub                        0.9.3    
jupyterhub-systemdspawner         0.11     
lxml                              4.2.5    
Mako                              1.0.7    
MarkupSafe                        1.0      
mistune                           0.8.3    
nbconvert                         5.4.0    
nbformat                          4.4.0    
nbgrader                          0.5.4    
nbtutor                           1.0.4    
notebook                          5.7.0    
pamela                            0.3.0    
pandocfilters                     1.4.2    
parso                             0.3.1    
pexpect                           4.6.0    
pickleshare                       0.7.4    
pip                               18.1     
prometheus-client                 0.3.1    
prompt-toolkit                    1.0.15   
ptyprocess                        0.6.0    
Pygments                          2.2.0    
python-dateutil                   2.7.3    
python-editor                     1.0.3    
python-oauth2                     1.1.0    
PyYAML                            3.13     
pyzmq                             17.1.2   
qtconsole                         4.4.1    
requests                          2.19.1   
Send2Trash                        1.5.0    
setuptools                        40.2.0   
simplegeneric                     0.8.1    
six                               1.11.0   
SQLAlchemy                        1.2.12   
terminado                         0.8.1    
testpath                          0.3.1    
tornado                           5.1.1    
traitlets                         4.3.2    
urllib3                           1.23     
wcwidth                           0.1.7    
webencodings                      0.5.1    
wheel                             0.31.1   
widgetsnbextension                3.4.2

**Comment by lgpage** [comment] 2021-07-29 17:53
Likely a duplicate of #30
Should be fixed by #44

**Closed** 2022-04-20 15:41 UTC
Labels: bug, duplicate
